### ISSUE TITLE
Please consider releasing your code via an open source license

### ISSUE THREAD

**Issue by awynne** [reta/spring-one-jar#1]
Since much of the code in your reta/ repository is example code on how to set up various frameworks to work together, I was hoping that you would consider releasing it under a business-friendly license.  I'm specifically interested in https://github.com/reta/spring-one-jar/tree/jetty-embedded.

Is this possible?  

Please note that if you don't include a license, no one can create derivative works from your code (https://help.github.com/articles/open-source-licensing).  If this is your intention, then I apologize for bothering you.

Your example code is very useful and a good resource so I hope you consider sharing it with the community.  :)

Thanks and Regards,
Adam

**Comment by reta** [comment]
Hi Adam,

Thank you very much for pointing out this very important issue, I totally disregarded it (my bad).
I am going to add Apache v2.0 open source license to all my repositories/branches, should be done shortly.
Thank you a lot, I am very pleased you found it useful.

Thanks!

Best Regards,
    Andriy Redko

**Comment by awynne** [comment]
Yes it has saved me a significant amount of time.

Thanks again!

**Comment by reta** [comment]
Done! You are welcome!
